### ISSUE TITLE
Unable to process coreos image

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#380]
Test data:
`curl -LO https://stable.release.core-os.net/amd64-usr/current/coreos_production_vmware_ova.ova`
`tar xfv coreos_production_vmware_ova.ova`

This is a hybrid MBR/GPT image.

```
source_analyzer.py coreos_production_vmware_ova_image.vmdk
Source type		: storage media image

OS: location: coreos_production_vmware_ova_image.vmdk
  VMDK: 
    TSK_PARTITION: location: /
      TSK_PARTITION: 0, start offset: 0 (0x00000000)
      TSK_PARTITION: 1, start offset: 0 (0x00000000)
      TSK_PARTITION: 2, start offset: 512 (0x00000200), location: /p1
      TSK_PARTITION: 3, start offset: 2097152 (0x00200000), location: /p2
        TSK: location: /
      TSK_PARTITION: 4, start offset: 136314880 (0x08200000)

Completed.
```

This behavior seems to be caused by libtsk/pytsk also see https://github.com/sleuthkit/sleuthkit/issues/1444

In contrast a GPT with a protective MBR

```
source_analyzer.py gpt_single.raw 
Source type		: storage media image

OS: location: gpt_single.raw
  RAW: 
    TSK_PARTITION: location: /
      TSK_PARTITION: 0, start offset: 0 (0x00000000)
      TSK_PARTITION: 1, start offset: 0 (0x00000000)
      TSK_PARTITION: 2, start offset: 512 (0x00000200)
      TSK_PARTITION: 3, start offset: 1024 (0x00000400)
      TSK_PARTITION: 4, start offset: 1048576 (0x00100000), location: /p1
      TSK_PARTITION: 5, start offset: 1114112 (0x00110000)

Completed.
```

So the behavior of pytsk/libtsk is not reliable here.
