### ISSUE TITLE
Improve source scanner

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#50]
/dev/rdisk1

```
Source type     : storage media image

OS: location: /dev/rdisk1
  RAW: 
    TSK: location: /
```
- [x] ~~[detect "storage media device" when "storage media image" is indicated](https://codereview.appspot.com/281030043/)~~
- [x] remove the indirect RAW ?
- [x] Have source scanner ignore false positives `TSK: location: /`
- [ ] ~~Create source scanner helpers - not for now~~

```
OS: location: image.qcow2
  QCOW: 
    TSK_PARTITION: location: /
      TSK_PARTITION: 0, start offset: 0 (0x00000000)
        TSK: location: /
      TSK_PARTITION: 1, start offset: 0 (0x00000000)
        TSK: location: /
      TSK_PARTITION: 2, start offset: 32256 (0x00007e00), location: /p1
        NTFS: location: \
      TSK_PARTITION: 3, start offset: 16096872960 (0x3bf72ca00)
```
